name: CI

on:
  push:
    branches: [ main ]

env:
  SOLUTION_NAME: GitHubActionsDemo.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_NAME }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_NAME }} /verbosity:quiet /p:Configuration=Release

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Run Unit tests
        run: vstest.console.exe **/bin/**/*.Tests.dll /TestCaseFilter:"TestCategory=UnitTests" /Parallel /Logger:"trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1

      - name: Parse tests results to JUnit xml
        if: ${{ false }} #always()
        run: |
          dotnet tool install -g trx2junit
          trx2junit ${{ github.workspace }}/TestResults/*.trx

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: ${{ false }} #always()
        with:
          files: ${{ github.workspace }}/TestResults/*.xml
